[package]
name = "take-home-2"
version = "0.1.0"
authors = ["pushthat <matias.berny@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libh3 = "0.1.8"
geo = "0.14.2"
geo-booleanop = "0.2.1"